# Site settings
title: Press Start
email: pete@laxaltandmciver.co
baseurl: ""
url: ""
permalink: pretty
destination: docs/
sass:
  sass_dir: _sass
  style: compressed

# Build settings
markdown: kramdown
